spring.profiles.default: local
spring.config:
  import:
    - classpath:/application-core.yml

server:
  port: 7000
  servlet:
    context-path: /community
    encoding:
      charset: UTF-8
      force: true

---
spring:
  config:
    activate:
      on-profile:
        - local
logging:
  level:
    org.springframework.cache: TRACE

---
spring:
  config:
    activate:
      on-profile:
        - test
logging:
  level:
    org.springframework.cache: TRACE
