spring.profiles.default: local
spring.config:
  import:
    - classpath:/application-core.yml

server:
  port: 7000
  servlet:
    context-path: /community
    encoding:
      charset: UTF-8
      force: true
  shutdown: graceful
  tomcat:
    threads:
      max: 300
      min-spare: 300
    connection-timeout: 5s

spring:
  main:
    web-application-type: servlet
  mvc:
    format:
      date: iso
      date-time: iso
      time: iso
    servlet:
      load-on-startup: 1
  messages:
    encoding: UTF-8

---
spring:
  config:
    activate:
      on-profile:
        - local
        - test
logging:
  level:
    org.springframework.cache: TRACE

sentry:
  enabled: false
  logging:
    enabled: false

---
spring:
  config:
    activate:
      on-profile:
        - dev
        - prod

sentry:
  dsn: ${secret.sentry.dsn}
  traces-sample-rate: 1.0
