spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 300
        query.in_clause_parameter_padding: true
    open-in-view: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 5000
  data:
    redis:
      timeout: 3000
      connect-timeout: 3000
      database: 0
      repositories:
        enabled: false


---
spring.config:
  activate:
    on-profile:
      - local

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mariadb://localhost:23306/community_local
    username: root
    password: community
    hikari:
      maximum-pool-size: 10
  data:
    redis:
      host: localhost
      port: 26379

---
spring.config:
  activate:
    on-profile:
      - test

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mariadb://localhost:33306/community_test
    username: root
    password: community
    hikari:
      maximum-pool-size: 10
  data:
    redis:
      host: localhost
      port: 36379

---
spring.config:
  activate:
    on-profile:
      - dev

# TODO: dev, prod 환경 설정 추가

---
spring.config:
  activate:
    on-profile:
      - prod

# TODO: dev, prod 환경 설정 추가
